id: A6B2B9BB9
title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin Nyima
type: translation
pechas:
- I84E809EA
- IA90958A9
- I0EE007AC
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:56:41.153606
  last_modified_at: 2023-01-04 12:56:41.153625
  collections:
  - Lama Rigdzin Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  I84E809EA/3FBD: '2489'
  IA90958A9/4211: '2489'
  I0EE007AC/C50C: '2489'
